name: CI

on: [push, pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ github.sha }}-node-modules
          restore-keys: |
            ${{ github.sha }}-node-modules
            ${{ github.run_id }}-node-modules
            node-modules

      - name: Install dependencies
        run: npm ci

  lint:
    needs: [install]
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ github.sha }}-node-modules
          restore-keys: |
            ${{ github.sha }}-node-modules
            ${{ github.run_id }}-node-modules
            node-modules

      - name: Lint
        run: npm run lint

  build:
    needs: [lint]
    runs-on: ubuntu-latest
    container:
      image: node:16
      options: --user root
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ github.sha }}-node-modules
          restore-keys: |
            ${{ github.sha }}-node-modules
            ${{ github.run_id }}-node-modules
            node-modules

      - name: Build
        run: npm run build
